name: Continuous Integration (CI)

on:
  workflow_dispatch:
  pull_request:
    branches: [dev]

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: build
        run: |
          pnpm prisma:generate
          pnpm build

      - name: Test
        run: pnpm test
